version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Vrhythms69@
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U SA -P 'Vrhythms69@' -Q 'SELECT 1'"]
      interval: 30s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crudDapperMapperAndDocker
    ports:
      - "5000:80"
    networks:
      - mynetwork
    depends_on:
      - sqlserver

networks:
  mynetwork:
    driver: bridge
